python src/main.py \
    --seed=0 \
    --data_dir="data" \
    --model_name="bert" \
    --num_epochs=1 \
    --train_batch_size=16 \
    --eval_batch_size=4 \
    --num_workers=4 \
    --max_encoder_len=512 \
    --num_decoder_layers=2 \
    --decoder_dropout=0.2 \
    --max_decoder_len=512 \
    --learning_rate=5e-5 \
    --warmup_prop=0.1 \
    --max_grad_norm=1.0 \
    --use_copy \
    --mtl_factor=1.0 \
    --beam_size=4 \
    --gpus="0" \
    --num_nodes=1